version: '3.8'

services:
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-dev
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=development
      - PORT=3333
      - AI_API_URL=https://generativelanguage.googleapis.com/v1beta/openai/chat/completions
      - AI_MODEL=gemini-2.0-flash
      - AI_API_KEY=sua_chave_local_aqui
      - MONGO_URL=mongodb://mongodb:27017/meuplanoai
      - CORS_ORIGIN=http://localhost:5173
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - meuplanoai_net

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3333
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - meuplanoai_net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - dados-do-mongo:/data/db
    networks:
      - meuplanoai_net

networks:
  meuplanoai_net:
    driver: bridge

volumes:
  dados-do-mongo: